config/routes.rb
Rails.application.routes.draw do
  get 'authentication/new'

  root 'index#index'
  get '/about' => 'index#about'
  get '/contact' => 'contact#new'

  get '/search' => 'search#index', as: :search_index
  resource :search, only:[:show]

  resources :clinicians
  resources :patients, only: [:index, :show]
  
  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
  end

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clinician.rb
class Clinician < ApplicationRecord
  has_secure_password
  
  include PgSearch
  has_many :patients, dependent: :nullify

  validates :first_name, presence: true
  validates :last_name, presence: true, uniqueness: {scope: :first_name}
  # validates :email, format: VALID_EMAIL_REGEX
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, :with => /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/
  validates :address, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true
  validates :password, presence: true
  validates :password_confirmation, presence: true


  multisearchable against: [:first_name, :last_name, :email, :phone]
end

app/models/data_api.rb
class DataApi < ApplicationRecord
  belongs_to :patient_log
end

app/models/fam_doc.rb
class FamDoc < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true, uniqueness: {scope: :first_name}
  validates :address, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_secure_password
  
  include PgSearch
  belongs_to :clinician
  has_many :patient_logs, dependent: :destroy

  after_initialize :set_handler_defaults

  validates :care_id, presence: true, uniqueness: true
  validates :care_handler, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true, uniqueness: {scope: :first_name}
  validates :sex, presence: true
  validates :age, presence: true
  # validates :email, presence: true, uniquness: true, format: VALID_EMAIL_REGEX
  validates :email, presence: true, uniqueness: true
  validates :phone, presence: true, uniqueness: true
  validates :address, presence: true, uniqueness: true
  validates :password, presence: true
  validates :password_confirmation, presence: true
  validates :clinician_id, presence: true
  validates :fam_doc_id, presence: true

  multisearchable against: [:care_id, :care_handler, :first_name, :last_name, :email, :phone]

  private

  def set_handler_defaults
    self.care_handler ||= 'Not Required'
  end
end

app/models/patient_log.rb
class PatientLog < ApplicationRecord
  belongs_to :patient
  has_many :data_apis, dependent: :destroy

  validates :patient_id, presence: true
  validates :date, presence: true
  validates :heartrate, presence: true
  validates :bp_hi, presence: true
  validates :bp_low, presence: true
  validates :weight, presence: true
  validates :exerting_breath, presence: true
  validates :night_breath, presence: true
  validates :leg_swollen, presence: true
  validates :lightheadedness, presence: true

end

app/models/patient_rec.rb
class PatientRec < ApplicationRecord
  validates :visit_date, presence: true
  validates :diagnoses, presence: true
  validates :diag_date, presence: true
  validates :new_prescription, presence: true
  validates :prescribed_date, presence: true
  validates :new_prescription_end, presence: true
  validates :clinician_id, presence: true
  validates :patient_id, presence: true
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
  
  end

  def about

  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!

  def index
    @limit ||= 25
    @data = Patient.order(id: :asc).page(params[:page]).per(@limit)
  end

  def show

  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!
  
  def index
    @limit ||= 15
    @query = params[:query]
    @pgsearch = PgSearch.multisearch(@query).includes(:searchable).map(&:searchable)
    # @results = @pgsearch.page(params[:page]).per(@limit)
  end

  def show
  end

  # def self.multisearch(query)
  #   PgSearch.multisearch(query).includes(:searchable).map(&:searchable)
  # end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/clinicians_helper.rb
module CliniciansHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/index/about.html.erb
<h1>About Page</h1>

app/views/index/index.html.erb
<h1>Home Page</h1>

app/views/layouts/applicatio(test).test.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Heart Companion</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header>
      <div class='container'>
        <ul id="nav-mobile" class="side-nav fixed">
          <li>
            <div class="userView">
            <img class="background" src="https://goo.gl/e6Op43">
            <a href="#!user"><img class="circle" src="http://goo.gl/qIgyox"></a>
            <a href="#!name"><span class="white-text name">Roderick Fung</span></a>
            <a href="#!email"><span class="white-text email">roderickfung@gmail.com</span></a>
            </div>
          </li>
          <li class='search'>
            <div class='search-wrapper card'>
              <input id='search'>
              <i class='material-icons'>search</i>
              <div class='search-results'></div>
              </input>
            </div>
          </li>
          <li>
            <%= link_to root_path do %>
              <i class="material-icons">dashboard</i>Dashboard
            <%end%>
          </li>
          <li class='no-padding'>
            <ul class="collapsible collapsible-accordion">
              <li>
                <a class="collapsible-header">Clinicians<i class="material-icons">arrow_drop_down</i></a>
                <div class="collapsible-body">
                  <ul>
                    <li><%= link_to("Clinicians List", clinicians_path)%></li>
                    <li><%= link_to("New Clinician", new_clinician_path)%></li>
                  </ul>
                </div>
              </li>
            </ul>
          </li>
          <li><a href="#!"><i class="material-icons">assignment_ind</i>Patient Data</a></li>
          <li><div class="divider"></div></li>
          <li><a class="subheader">Subheader</a></li>
          <li><a class="waves-effect" href="#!">asdasdfa</a></li>
        </ul>
      </div>
    </header>
      <!-- Page Content -->
    <main>
      <div class="container">
        <div class='row'>
          <div class='col s12 m9 l10'>
            <!-- <div class = 'menu-btn'>
              <a href="#" data-activates="slide-out" class="button-collapse"><i class="small material-icons">menu</i></a>
            </div> -->
            <!-- <div class="container-fluid"> -->
              <!-- <div class="row"> -->
                  <!-- <div class="col-lg-12"> -->
                      <%=yield%>
                  <!-- </div> -->
              <!-- </div> -->
            <!-- </div> -->
          </div>
        </div>
      </div>
    </main>
</body>
</html>
<script>
// Initialize collapse button
$(".button-collapse").sideNav({
  menuWidth: 300, // Default is 240
  edge: 'left', // Choose the horizontal origin
  closeOnClick: true // Closes side-nav on <a> clicks, useful for Angular/Meteor
});
// Initialize collapsible (uncomment the line below if you use the dropdown variation)
// $('.collapsible').collapsible();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Heart Companion</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <header>
      <div class='container'>
        <ul id="slide-out" class="side-nav fixed" style="transform: translateX(0%);">
          <li>
            <div class="userView">
              <img class="responsive-img background" src="http://www.w3schools.com/w3css/img_fjords.jpg">
              <a href="#!user"><img class="circle responsive-img" src="http://goo.gl/qIgyox"></a>
              <a href="#!name"><span class="white-text name">Roderick Fung</span></a>
              <a href="#!email"><span class="white-text email">roderickfung@gmail.com</span></a>
            </div>
          </li>
          <li class="search">
            <div class="">
              <div class="search-bar">
                <%= form_tag search_path, method: 'get', class: 'search-wrapper card', role: 'search' do %>
                  <div class='input-group'>
                    <%= text_field_tag :query, params[:query], size: 150, placeholder: "Search", class: "form-control"%>
                    <%= button_tag(type: 'submit', class: 'btn-floating waves-effect waves-light btn', name: nil) do %>
                      <i class='material-icons'>search</i>
                    <%end%>
                  </div>
                <% end %>
              </div>
            </div>
          </li>
          <li>
            <%= link_to root_path do %>
              <i class="material-icons">dashboard</i>Dashboard
            <%end%>
          </li>
          <li class='no-padding'>
            <ul class="collapsible collapsible-accordion">
              <li>
                <a class="collapsible-header">Clinicians<i class="material-icons">arrow_drop_down</i></a>
                <div class="collapsible-body">
                  <ul>
                    <li><%= link_to("Clinicians List", clinicians_path)%></li>
                    <li><%= link_to("New Clinician", new_clinician_path)%></li>
                  </ul>
                </div>
              </li>
            </ul>
          </li>
          <li><a href="#!"><i class="material-icons">assignment_ind</i>Patient Data</a></li>
          <li><div class="divider"></div></li>
          <li><a class="subheader">Subheader</a></li>
          <li><a class="waves-effect" href="#!">asdasdfa</a></li>
          <li>
            <div class='account-btn'>
              <%= link_to new_session_path do %>
              <i class='tiny material-icons'>settings</i> Account Settings
              <%end%>
            </div>
          </li>
        </ul>
      </div>
    </header>
      <!-- Page Content -->
    <main>
      <div class="container">
        <a href="#" data-activates="slide-out" class="button-collapse menu-btn"><i class="material-icons">menu</i></a>
        <%=yield%>
      </div>
    </main>
</body>
</html>
<script>
// Initialize collapse button
 $(".button-collapse").sideNav({
   menuWidth: 300,
   edge: 'left',
   closeOnclick: true
 });
 // Initialize collapsible (uncomment the line below if you use the dropdown variation)
 $('.collapsible').collapsible();
</script>

app/views/layouts/backup_application.text.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ChfApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse navbar-static-top" style = 'width: 15%%; background-color: #111111;'>
      <div class="container-fluid">
        <ul class="nav navbar-nav">
        <!-- <ul class="nav nav-tabs nav-stacked"> -->
          <li><%=link_to 'Home', root_path%></li>
          <li><%=link_to 'About', about_path%></li>
          <li class='dropdown'>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Database<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%=link_to 'Clinicians', clinicians_path%></li>
              <li><%=link_to 'Patients', patients_path%></li>
            </ul>
          </li>
          <li><%=link_to 'Contact', contact_path%></li>
        </ul>
      </div>
    </nav>
    <div class='container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Heart Companion</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <!-- Page Content -->
    <div class="container">
      <%=yield%>
    </div>
</body>
</html>